### ISSUE TITLE
Updating removes all user data

### ISSUE THREAD

**Issue by ltguillaume** [Ast3risk-ops/spotx-bucket#1]
I just updated to v1.2.20.1214, but this seems to launch the full uninstaller script. As a result, all user data is removed. I don't think it's desirable to need to log in again and change all settings every time an update is installed.

**Comment by Ast3risk-ops** [comment]
The flags set mean it automatically uninstalls your current spotify, same as `spotx-np`. It then installs the latest spotify through the spotx script.

**Comment by Ast3risk-ops** [comment]
This issue is really a spotx thing you have to live with, if you have an issue, report it to https://github.com/amd64fox/spotx

**Comment by Ast3risk-ops** [comment]
@ltguillaume Feel free to comment here if you have anything else.

**Comment by ltguillaume** [comment]
Ah sorry about that. I looked into the switches of SpotX quickly, but I didn't see anything other than an uninstall of the Spotify MS version. But I'm talking about updating from a lower version of SpotX to a new version of SpotX, both installed via your bucket.

**Comment by Ast3risk-ops** [comment]
> Ah sorry about that. I looked into the switches of SpotX quickly, but I didn't see anything other than an uninstall of the Spotify MS version. But I'm talking about updating from a lower version of SpotX to a new version of SpotX, both installed via your bucket.

nono, scoop runs the uninstall script, then the install script, the uninstall script removes your current spotify. @ltguillaume

**Comment by Ast3risk-ops** [comment]
Same behavior as `spotx-np` from Nonportable (but as you know that version is broken because nobody merged amd64fox's PR).

**Comment by ltguillaume** [comment]
Right! I didn't know that Scoop also runs the uninstaller script before every update. Seems strange to me, or it should at least be configurable per manifest imho.

What I did find is that the "normal" Spotify manifest works around this by adding
```
if ($cmd -ne 'uninstall') { return }
```

**Comment by Ast3risk-ops** [comment]
@ltguillaume where? I guess you could provide a link and I could look into this

**Comment by ltguillaume** [comment]
https://github.com/ltguillaume/schep/blob/main/bucket/spotx.json

**Comment by ltguillaume** [comment]
https://github.com/ScoopInstaller/Extras/blob/f0fa776d588abd09317b912ad56d68a5017f49f4/bucket/spotify.json#L29

**Comment by Ast3risk-ops** [comment]
Potentially this was removed for a silent install, spotx would normally ask the user to either install over or uninstall then install new.

**Comment by Ast3risk-ops** [comment]
https://github.com/Ast3risk-ops/spotx-bucket/commit/32248512b7a477f471915ea6ffdc00d79e275ef3

**Comment by ltguillaume** [comment]
Great! Thank you for the update!

> Potentially this was removed for a silent install, spotx would normally ask the user to either install over or uninstall then install new.

Ah, could be, but the side effect is much worse I would say!

**Comment by Ast3risk-ops** [comment]
Never mind there's a flag to set that too

**Comment by Ast3risk-ops** [comment]
Just fixing some issues with the last commit, I'll tell you once the tests succeed.

**Comment by Ast3risk-ops** [comment]
@ltguillaume also thanks for using my bucket. It did make it onto scoop search, but it's mostly other buckets with a bunch of tools.

**Comment by Ast3risk-ops** [comment]
tests succeeded

**Comment by Ast3risk-ops** [comment]
Feel free to test everything out and tell me if something goes wrong.

**Comment by ltguillaume** [comment]
Thanks!

Yes, I like single-purpose bucket to be honest! Feels like less overhead and it's fast when updating.

**Comment by Ast3risk-ops** [comment]
I suck at powershell so this method was easiest.

**Comment by Ast3risk-ops** [comment]
The excavator runs every hour, so @ltguillaume an update should be soon and you can tell me if it worked then.

**Comment by ltguillaume** [comment]
FYI, see https://github.com/ScoopInstaller/Scoop/discussions/5648

**Comment by ltguillaume** [comment]
@Ast3risk-ops Today I got to update to 1.21 and it worked nicely, without the loss of user data. I created a PR for the Scoop update procedure to solve this for all other apps, too (see previous post), but I haven't gotten a reply yet.

**Comment by Ast3risk-ops** [comment]
Great!
